### ISSUE TITLE
Search-box completion doesn't account for auto-redirects

### ISSUE THREAD

**Issue by matthew-cline** [locriani/magmawiki#15]
A link to (for example) "Wheelbarrow" will automatically redirect to "DF2014:Wheelbarrow" without the need for a redirect page.  However, the search-box's drop-down completion list does do that, so typing "Wheel" into the search box makes it look like there aren't any articles starting with "Wheel".

**Comment by lethosor** [comment]
This repo actually isn't the code used on the DF wiki (we still use MediaWiki). I've moved this over to DF-Wiki/DF-Wiki, which is our (not very) new public repo/issue tracker.
(Regarding this issue, I've been meaning to sort it out for a while but haven't gotten around to it.)
