### ISSUE TITLE
Use guard instead of autotest?

### ISSUE THREAD

**Issue by NobbZ** [locriani/magmawiki#4]
Hi!

Since I am using guard for my private projects, I got a hang on it :D

But I really think besides personal preferences, it is worth the discussion.

guard is a small ruby tool, that watches the files in the application and starts its submodules on certain changes. guard is hosted on github and can be found there --> https://github.com/guard/guard

Autotest only runs tests, feautures and specs. Guard is able to do much, much more like restart the dev server on config changes ([guard-rails](https://github.com/guard/guard-rails)), it can install new Gems when Gemfile was updated ([guard-bundler](https://github.com/guard/guard-bundler)) and even run specs ([guard-rspec](https://github.com/guard/guard-rspec)) or features ([rspec-cucumber](https://github.com/guard/guard-cucumber))

All thinks that make development much more fluid (I think).

If you have use for them, there are much more guard modules (https://github.com/guard/guard/wiki/List-of-available-Guards), perhaps you can find a way to use them, that I missed so far.

**Comment by NobbZ** [comment]
I did conversion from autotest to guard in my [feature/guard-branch](https://github.com/NobbZ/Magmawiki/tree/feature/guard), but cant find pull request button...

You could take a look at it, or just leave it alone, but please tell me your decission :D

**Comment by NobbZ** [comment]
Sorry for close, hit the wrong button :D

**Comment by locriani** [comment]
I'll look into this.  Shortly, I will soon have more free time!

**Comment by epitron** [comment]
OPEN ISSUE.

**Comment by locriani** [comment]
It's far too easy to press the Comment & Close button.  Github should make it red or something :/

**Comment by epitron** [comment]
Yeah.. Especially since "Close" usually means "Close this window", not "NEVER SEE AGAIN".

**Comment by PManager1** [comment]
I moved to guard

**Comment by locriani** [comment]
Guard is default on develop.
