### ISSUE TITLE
rspec and shoulda?

### ISSUE THREAD

**Issue by NobbZ** [locriani/magmawiki#5]
Why are there rspec and shoulda in the Gemfile?

So far as I can tell both are used for the same purpose, they are both a replacement for unit tests, or do I missunderstand things?

Additionally it seems that shoulda is not really used in the tests, so can we remove it safely?

**Comment by NobbZ** [comment]
Also I think a cleanup of features, specs or/and tests is quite necessary. I think this cleanup fits very well into the fact that there are two testing frameworks required in the Gemfile...

**Comment by epitron** [comment]
Agreed. I just committed what I was working on yesterday -- removing extraneous things from the Gemfile.

The tests are out of date in other ways too -- Factory Girl deprecated the use of the 'Factory' module.

Nothing complicated... just a little maintenance work. :)

**Comment by locriani** [comment]
Shoulda extends RSpec functionality, it's not a separate test / test harness framework.

**Comment by epitron** [comment]
Whoops, sorry. I was confusing it with bacon or something.
